Traceback (most recent call last):
  File "/scratch/lfs/mcintyre/staph_DNA/scripts/filter_contigs_by_length_500bp_amm6.py", line 48, in <module>
    main()
  File "/scratch/lfs/mcintyre/staph_DNA/scripts/filter_contigs_by_length_500bp_amm6.py", line 45, in main
    fastq_reader(args)
  File "/scratch/lfs/mcintyre/staph_DNA/scripts/filter_contigs_by_length_500bp_amm6.py", line 20, in fastq_reader
    for record in SeqIO.parse(args.fname, "fasta") :
  File "/apps/python/2.7.6/lib/python2.7/site-packages/Bio/SeqIO/__init__.py", line 572, in parse
    with as_handle(handle, mode) as fp:
  File "/apps/python/2.7.6/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/apps/python/2.7.6/lib/python2.7/site-packages/Bio/File.py", line 90, in as_handle
    with open(handleish, mode, **kwargs) as fp:
IOError: [Errno 2] No such file or directory: '/scratch/lfs/mcintyre/staph_DNA/spades_output_all_strains/spades_output_all_strains/CDI_1572/scaffolds.fasta'
